layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name
topics:
  - name: Historical Trivia (I dabbled a bit in High School)
    web_url: https://globalnation.inquirer.net/142283/ph-places-5th-in-intl-history-olympiad-medal-count
    image_url: https://img-9gag-fun.9cache.com/photo/amBypO6_700bwp.webp

  - name: Cycling
    web_url: https://www.strava.com/athletes/50452660
    image_url: https://i.imgur.com/prQ72fc.jpg

  - name: Philosophy
    web_url: https://www.iep.utm.edu/consciou/
    image_url: https://i.pinimg.com/originals/b6/e6/ec/b6e6ec61a6e233194d64dbecef169c9f.jpg
